import { execFile } from 'node:child_process';
import { mkdtemp, rm, writeFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join } from 'node:path';
import { fileURLToPath } from 'node:url';
import { promisify } from 'node:util';
import { describe, expect, it } from 'vitest';

const execFileAsync = promisify(execFile);

const localizationFixturePath = fileURLToPath(
  new URL(
    '../../.build/shared/elder-terms-localization-fixture',
    import.meta.url
  )
);

const translations = [
  {
    language: 'ar',
    webdavMessages: [
      'أمان الاتصال',
      'المسار المنشور',
      'المصادقة',
      'مهلة الاتصال (بالثواني)',
      'مهلة الخمول (بالثواني)',
      'HTTPS (مشفّر)',
      'HTTP (غير مشفّر)',
      'تلقائي (Basic أو Digest)',
      'أدخل قيمة صالحة',
      'أكمل إعدادات الاتصال لمعاينة عنوان URL',
      'عنوان URL للاتصال',
      'مصادقة WebDAV',
      'تعذّر بدء WebDAV',
      'فشل التحقق من شهادة HTTPS',
      'اتصال HTTPS',
      'مجلد جديد',
      'إنشاء',
      'أدخل اسمًا للمجلد الجديد.',
      'جارٍ إنشاء المجلد…',
      'تعذّر إنشاء المجلد',
      'أُلغي إنشاء المجلد',
      'أُنشئ المجلد "%s"',
      'WebDAV',
      'Basic',
      'Digest',
    ],
    settings: 'الإعدادات',
    links: 'الروابط',
    hashMessages: [
      'جارٍ حساب قيم التجزئة…',
      'أُلغي حساب قيم التجزئة',
      'فشل حساب قيم التجزئة',
      'تعذر حساب قيم التجزئة',
      'اكتمل حساب قيم التجزئة',
      'قيم تجزئة الملف',
      'حساب قيم التجزئة',
    ],
  },
  {
    language: 'es',
    webdavMessages: [
      'Seguridad de la conexión',
      'Ruta publicada',
      'Autenticación',
      'Tiempo de espera de conexión (segundos)',
      'Tiempo de espera por inactividad (segundos)',
      'HTTPS (cifrado)',
      'HTTP (sin cifrar)',
      'Automática (Basic o Digest)',
      'Introduzca un valor válido',
      'Complete la configuración de conexión para ver la URL',
      'URL de conexión',
      'Autenticación WebDAV',
      'No se pudo iniciar WebDAV',
      'Error al validar el certificado HTTPS',
      'Conexión HTTPS',
      'Nueva carpeta',
      'Crear',
      'Introduzca un nombre para la nueva carpeta.',
      'Creando carpeta…',
      'No se pudo crear la carpeta',
      'Creación de carpeta cancelada',
      'Carpeta "%s" creada',
      'WebDAV',
      'Basic',
      'Digest',
    ],
    settings: 'Configuración',
    links: 'Enlaces',
    hashMessages: [
      'Calculando valores hash…',
      'Cálculo de hash cancelado',
      'Error al calcular el hash',
      'No se pudieron calcular los valores hash',
      'Cálculo de hash completado',
      'Valores hash del archivo',
      'Calcular valores hash',
    ],
  },
  {
    language: 'fr',
    webdavMessages: [
      'Sécurité de la connexion',
      'Chemin publié',
      'Authentification',
      'Délai de connexion (secondes)',
      'Délai d’inactivité (secondes)',
      'HTTPS (chiffré)',
      'HTTP (non chiffré)',
      'Automatique (Basic ou Digest)',
      'Saisissez une valeur valide',
      'Complétez les paramètres de connexion pour afficher l’URL',
      'URL de connexion',
      'Authentification WebDAV',
      'Impossible de démarrer WebDAV',
      'Échec de la validation du certificat HTTPS',
      'Connexion HTTPS',
      'Nouveau dossier',
      'Créer',
      'Saisissez un nom pour le nouveau dossier.',
      'Création du dossier…',
      'Impossible de créer le dossier',
      'Création du dossier annulée',
      'Dossier « %s » créé',
      'WebDAV',
      'Basic',
      'Digest',
    ],
    settings: 'Paramètres',
    links: 'Liens',
    hashMessages: [
      'Calcul des valeurs de hachage…',
      'Calcul des valeurs de hachage annulé',
      'Échec du calcul des valeurs de hachage',
      'Impossible de calculer les valeurs de hachage',
      'Calcul des valeurs de hachage terminé',
      'Valeurs de hachage du fichier',
      'Calculer les valeurs de hachage',
    ],
  },
  {
    language: 'hi',
    webdavMessages: [
      'कनेक्शन सुरक्षा',
      'प्रकाशित पथ',
      'प्रमाणीकरण',
      'कनेक्शन समय सीमा (सेकंड)',
      'निष्क्रियता समय सीमा (सेकंड)',
      'HTTPS (एन्क्रिप्टेड)',
      'HTTP (अनएन्क्रिप्टेड)',
      'स्वचालित (Basic या Digest)',
      'मान्य मान दर्ज करें',
      'URL का पूर्वावलोकन करने के लिए कनेक्शन सेटिंग पूरी करें',
      'कनेक्शन URL',
      'WebDAV प्रमाणीकरण',
      'WebDAV शुरू नहीं हो सका',
      'HTTPS प्रमाणपत्र का सत्यापन विफल हुआ',
      'HTTPS कनेक्शन',
      'नया फ़ोल्डर',
      'बनाएँ',
      'नए फ़ोल्डर का नाम दर्ज करें।',
      'फ़ोल्डर बनाया जा रहा है…',
      'फ़ोल्डर नहीं बनाया जा सका',
      'फ़ोल्डर बनाना रद्द किया गया',
      'फ़ोल्डर "%s" बनाया गया',
      'WebDAV',
      'Basic',
      'Digest',
    ],
    settings: 'सेटिंग्स',
    links: 'लिंक',
    hashMessages: [
      'हैश मानों की गणना की जा रही है…',
      'हैश मान गणना रद्द की गई',
      'हैश मान गणना विफल रही',
      'हैश मानों की गणना नहीं हो सकी',
      'हैश मान गणना पूरी हुई',
      'फ़ाइल हैश मान',
      'हैश मानों की गणना करें',
    ],
  },
  {
    language: 'ja',
    webdavMessages: [
      '接続の暗号化',
      '公開パス',
      '認証方式',
      '接続タイムアウト（秒）',
      '無通信タイムアウト（秒）',
      'HTTPS（暗号化）',
      'HTTP（暗号化なし）',
      '自動（BasicまたはDigest）',
      '有効な値を入力して下さい',
      '接続設定を入力するとURLを表示します',
      '接続URL',
      'WebDAV認証',
      'WebDAV接続を開始できませんでした',
      'HTTPS証明書の検証に失敗しました',
      'HTTPS接続',
      '新しいフォルダー',
      '作成',
      '新しいフォルダーの名前を入力して下さい。',
      'フォルダーを作成中…',
      'フォルダーを作成できませんでした',
      'フォルダーの作成を取り消しました',
      'フォルダー「%s」を作成しました',
      'WebDAV',
      'Basic',
      'Digest',
    ],
    settings: '設定',
    links: 'リンク',
    hashMessages: [
      'ハッシュ値を計算中…',
      'ハッシュ値の計算をキャンセルしました',
      'ハッシュ値の計算に失敗しました',
      'ハッシュ値を計算できませんでした',
      'ハッシュ値の計算が完了しました',
      'ファイルのハッシュ値',
      'ハッシュ値を計算',
    ],
  },
  {
    language: 'ko',
    webdavMessages: [
      '연결 보안',
      '공개 경로',
      '인증',
      '연결 시간 제한(초)',
      '유휴 시간 제한(초)',
      'HTTPS(암호화)',
      'HTTP(암호화 안 함)',
      '자동(Basic 또는 Digest)',
      '올바른 값을 입력하세요',
      '연결 설정을 입력하면 URL을 표시합니다',
      '연결 URL',
      'WebDAV 인증',
      'WebDAV를 시작하지 못했습니다',
      'HTTPS 인증서 검증에 실패했습니다',
      'HTTPS 연결',
      '새 폴더',
      '만들기',
      '새 폴더의 이름을 입력하세요.',
      '폴더 만드는 중…',
      '폴더를 만들지 못했습니다',
      '폴더 만들기가 취소되었습니다',
      '"%s" 폴더를 만들었습니다',
      'WebDAV',
      'Basic',
      'Digest',
    ],
    settings: '설정',
    links: '링크',
    hashMessages: [
      '해시 값을 계산하는 중…',
      '해시 값 계산이 취소되었습니다',
      '해시 값 계산에 실패했습니다',
      '해시 값을 계산하지 못했습니다',
      '해시 값 계산이 완료되었습니다',
      '파일 해시 값',
      '해시 값 계산',
    ],
  },
  {
    language: 'pt',
    webdavMessages: [
      'Segurança da conexão',
      'Caminho publicado',
      'Autenticação',
      'Tempo limite de conexão (segundos)',
      'Tempo limite de inatividade (segundos)',
      'HTTPS (criptografado)',
      'HTTP (sem criptografia)',
      'Automática (Basic ou Digest)',
      'Insira um valor válido',
      'Preencha as configurações de conexão para visualizar a URL',
      'URL de conexão',
      'Autenticação WebDAV',
      'Não foi possível iniciar o WebDAV',
      'Falha na validação do certificado HTTPS',
      'Conexão HTTPS',
      'Nova pasta',
      'Criar',
      'Insira um nome para a nova pasta.',
      'Criando pasta…',
      'Não foi possível criar a pasta',
      'Criação da pasta cancelada',
      'Pasta "%s" criada',
      'WebDAV',
      'Basic',
      'Digest',
    ],
    settings: 'Configurações',
    links: 'Links',
    hashMessages: [
      'Calculando valores de hash…',
      'Cálculo de hash cancelado',
      'Falha no cálculo de hash',
      'Não foi possível calcular os valores de hash',
      'Cálculo de hash concluído',
      'Valores de hash do arquivo',
      'Calcular valores de hash',
    ],
  },
  {
    language: 'ru',
    webdavMessages: [
      'Защита соединения',
      'Опубликованный путь',
      'Аутентификация',
      'Время ожидания соединения (секунды)',
      'Время ожидания при бездействии (секунды)',
      'HTTPS (с шифрованием)',
      'HTTP (без шифрования)',
      'Автоматически (Basic или Digest)',
      'Введите допустимое значение',
      'Заполните параметры соединения для просмотра URL',
      'URL соединения',
      'Аутентификация WebDAV',
      'Не удалось запустить WebDAV',
      'Не удалось проверить сертификат HTTPS',
      'Соединение HTTPS',
      'Новая папка',
      'Создать',
      'Введите имя новой папки.',
      'Создание папки…',
      'Не удалось создать папку',
      'Создание папки отменено',
      'Создана папка «%s»',
      'WebDAV',
      'Basic',
      'Digest',
    ],
    settings: 'Настройки',
    links: 'Ссылки',
    hashMessages: [
      'Вычисление хеш-значений…',
      'Вычисление хеш-значений отменено',
      'Не удалось вычислить хеш-значения',
      'Не удалось вычислить хеш-значения',
      'Вычисление хеш-значений завершено',
      'Хеш-значения файла',
      'Вычислить хеш-значения',
    ],
  },
  {
    language: 'zh',
    webdavMessages: [
      '连接安全',
      '发布路径',
      '身份验证',
      '连接超时（秒）',
      '空闲超时（秒）',
      'HTTPS（加密）',
      'HTTP（未加密）',
      '自动（Basic 或 Digest）',
      '请输入有效值',
      '填写连接设置以预览 URL',
      '连接 URL',
      'WebDAV 身份验证',
      '无法启动 WebDAV',
      'HTTPS 证书验证失败',
      'HTTPS 连接',
      '新建文件夹',
      '创建',
      '请输入新文件夹的名称。',
      '正在创建文件夹…',
      '无法创建文件夹',
      '已取消创建文件夹',
      '已创建文件夹“%s”',
      'WebDAV',
      'Basic',
      'Digest',
    ],
    settings: '设置',
    links: '链接',
    hashMessages: [
      '正在计算哈希值…',
      '已取消哈希值计算',
      '哈希值计算失败',
      '无法计算哈希值',
      '哈希值计算完成',
      '文件哈希值',
      '计算哈希值',
    ],
  },
] as const;

describe('localization message catalogs', () => {
  it.each(translations)(
    'loads the $language catalog through the configured UI language',
    async ({ language, settings, links, hashMessages, webdavMessages }) => {
      const directory = await mkdtemp(
        join(tmpdir(), 'elder-terms-localization-')
      );
      const configPath = join(directory, 'global.ini');
      try {
        await writeFile(
          configPath,
          `[general]\nui_language=${language}\n`,
          'utf8'
        );
        const { stdout } = await execFileAsync(
          localizationFixturePath,
          [configPath],
          {
            env: {
              ...process.env,
              LANGUAGE: 'C',
              LC_ALL: 'C.UTF-8',
            },
          }
        );

        expect(stdout.trim()).toBe(
          [settings, links, ...hashMessages, ...webdavMessages].join('\n')
        );
      } finally {
        await rm(directory, { recursive: true, force: true });
      }
    }
  );
});
